#EXP: 9
#NAME:Rudransh Sharma
#PRN: 25070123096
#AIM: STUDY OF NUMPY LIBRARY


In [4]:

# Declration of Numpy
import numpy as np

a = np.array([1 , 10 , 20 , 30 , 40 , 50 , 500 ])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [7]:
# Dmension of Array
print(a.ndim)
print(b.ndim)

1
2


In [30]:
#To find shape

a.shape
b.shape
print(a.shape)
print(b.shape)

# To find data type

print(a.dtype)
print(b.dtype)

#In-Built function using Numpy
#zeros

print(np.zeros((2,3)))

#ones

print(np.ones((3,3)))

#eye

print(np.eye(3))

#arrange

print(np.arange(1,10,2))

#linspace

print(np.linspace(0,1,4))

#mean

print(np.mean(a))

#median

print(np.median(a))

#standard deviation

print(np.std(a))

#max value

print(np.max(a))

#min value

print(np.min(a))

#sum
print(np.sum(a))

(7,)
(2, 3)
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
93.0
30.0
166.88661677061722
500
1
651


In [23]:
#Decalaration of numpy
import numpy as np
a = np.array([1 , 10 , 20 , 30 , 40 , 50 , 500 ])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print(a+5)
print(b*2)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
[  6  15  25  35  45  55 505]
[[ 2  4  6]
 [ 8 10 12]]
